# Generated by Django 3.1.2 on 2020-10-15 00:48

import cms_blocks.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_title', models.BooleanField(default=True)),
                ('body', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Title text to display', required=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Bold title text for this card (len=255)', max_length=255, null=True, required=False)), ('text', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Optional text for this card', null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image - auto-cropped 570x370px', required=False)), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(blank=True, default='More details', max_length=50, required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page'))])))])), ('image_and_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('full', 'Full width centered'), ('left', 'Image to the left'), ('right', 'Image to the right')], help_text='Full image - text below, Image left - text right, or image right - text left.')), ('image_size', wagtail.core.blocks.ChoiceBlock(choices=[('standard', 'Standard 786x552'), ('landscape', 'Landscape 786x1104'), ('portrait', 'Portrait 786x300')], help_text='Layout - match with picture dimensions')), ('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Max length of 60 characters.', max_length=60, null=True, required=False)), ('text', wagtail.core.blocks.RichTextBlock(blank=True, features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough'], help_text='Description for this item', required=False)), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(blank=True, default='More details', max_length=50, required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], blank=True, null=True))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Max length of 60 characters, optional', max_length=60, null=True, required=False)), ('text', wagtail.core.blocks.RichTextBlock(blank=True, features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough'], help_text='Call to action text, optional (max=200)', required=False)), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(blank=True, default='More details', max_length=50, required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], blank=True, null=True))])), ('table', cms_blocks.blocks.CustomTableBlock()), ('richtext', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Display title, optional (max len=120)', max_length=120, null=True, required=False)), ('content', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough'], help_text='Rich text block, required'))])), ('testimonial', cms_blocks.blocks.TestimonialChooserBlock(help_text='Select testimonial')), ('large_image', cms_blocks.blocks.LargeImageChooserBlock(help_text='A large image')), ('new_section', wagtail.core.blocks.StructBlock([], help_text='Start a new section'))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tags', to='cms.cmspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_pagetag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cmspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Optional tags used to search for this page', through='cms.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
